[[section-introduction-and-goals]]


[role="arc42help"]
****
		
****
== Introducción y Metas
El proyecto trata de una aplicación de compra y venta de objetos cuyo codigo fuente sera realizado con "TypeScript"

Objetivos de Negocio: 

	-A corto plazo: Realizar una documentación adecuada de manera que se cumplan las 
	expectativas y necesidades del proyecto.
	-A largo plazo: Poder realizar una aplicación de manera que cumpla todos los objetivos 
	de usabilidad para poder realizar compra/venta de *ropa/objetos...* de una manera mas 
	cómoda,sencilla y accesible.

[role="arc42help"]
****
****

=== Vista de Requerimientos
Se necesitara una pequeña base de Typescript para la implementación de código de la aplicación y el uso de 
react para la implementación de cara al usuario.

Para realizar el control de versiones es necesario el uso de git, herramienta muy util para trabajos de 
gran tamaño permitiendo el uso de varias ramas para no alterar los prototipos del proyecto.

[role="arc42help"]
****
****
=== Metas de calidad
	-Trabajo entregado por parte de todos los participantes de una manera constante, puntual y correcta
	facilitando la evolución de la aplicación.
	-Implicación individual de cumplir las tareas asignadas.
	-Asegurar la limpieza y pulcritud del código.
	-Realizar reuniones para realizar actas o análisis dentro de los intervalos de tiempo comprometidos.
	-Que sea una aplicación vistosa/sencilla de usar.

[role="arc42help"]
****

****
=== Partes interesadas (Stakeholders)

[options="header",cols="1,2"]
|===
|Role/Name|Expectations| 
Administradores |Realizar una administración cómoda y sin inconvenientes.
| Equipo de desarrollo|Esperan poder obtener una aplicacíon correcta y usable.
| Cliente | Sus expectativas son poder realizar una compra en la aplicación de una manera sencilla y accesible.
|===

Administradores: 
Equipo de desarrollo: Que deben conocer la arquitectura de TypeScript, React y Solid.Deben trabajar de manera que se documente
todo el código para facilitar el entendimiento por parte de los demás miembros del grupo. Deben realizar reuniones para 
plantear las arquitecturas a usar. Por ejemplo: Para el desarrollo de Diagramas de secuencia.

Cliente: Quien interactuaría con la version final de la aplicacíon para la realización de compra
de Objetos.
